---
- name: Deploy web application
  hosts: web_servers
  become: yes
  vars_files:
    - vars/main.yml

  tasks:
    - name: Install required packages
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - python3
        - python3-pip
        - nginx

    - name: Configure Nginx
      template:
        src: templates/nginx.conf.j2
        dest: /etc/nginx/sites-available/webapp
      notify: restart nginx

    - name: Enable webapp site
      file:
        src: /etc/nginx/sites-available/webapp
        dest: /etc/nginx/sites-enabled/webapp
        state: link
      notify: restart nginx

    - name: Deploy the application code
      git:
        repo: "{{ webapp_git_repo }}"
        dest: /var/www/webapp

    - name: Install application dependencies
      pip:
        requirements: /var/www/webapp/requirements.txt
        state: present
    
    - name: Copy the configuration file
      copy:
        src: files/config.ini
        dest: /var/www/webapp/config.ini
        mode: 0644

    - name: Start the required services
      systemd:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - nginx
        - "{{ webapp_service_name }}"

  handlers:
    - name: restart nginx
      systemd:
        name: nginx
        state: restarted
